#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Aliases
if [ `uname` = 'Linux' ]; then
  alias update='sudo apt-get update'
  alias upgrade='sudo apt-get dist-upgrade'
  alias search='apt-cache search'
  alias install='sudo apt-get install'
  alias purge='sudo apt-get autoremove --purge'
  alias clean='sudo apt-get autoremove --purge && sudo apt-get autoclean'
  alias upup='update && upgrade'
  alias ppa='sudo add-apt-repository'
fi

if [ `uname` = 'Darwin' ]; then
  alias l='ls'
  alias vim='/Applications/MacVim.app/Contents/MacOS/Vim' # Use compiled terminal Vim
fi

# Load local custom configurations
if [ -e "$HOME/.zlocalrc" ]; then
  [[ -s "$HOME/.zlocalrc" ]] && source "$HOME/.zlocalrc"
fi

# LS_COLORS
eval $(dircolors -b ~/.LS_COLORS)

# Enable fasd
eval "$(fasd --init auto)"
alias v='f -e vim' # run vim on the most frecent file matching parameter
